name: C/C++ CI

on:
  push:
    paths-ignore:
    - '**/*.md'
  pull_request:
    paths-ignore:
    - '**/*.md'

jobs:
  ubuntu:
    runs-on: ubuntu-latest
    env:
      TERM: xterm
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: sudo apt-get install -y gettext
    - run: sudo python3 -m pip install meson ninja
    - run: |
        meson builddir
        ninja -v -C builddir
        ninja -C builddir dist
        meson --reconfigure builddir -Dnls=false
        ninja -v -C builddir

  macos:
    runs-on: macos-latest
    env:
      PKG_CONFIG_PATH: "/usr/local/opt/ncurses/lib/pkgconfig:$PKG_CONFIG_PATH"
      TERM: xterm
    steps:
    - uses: actions/checkout@v2
    - run: |
        brew update
        brew install ncurses meson
    - run: |
        meson builddir
        ninja -v -C builddir
        ninja -C builddir dist
