name: C/C++ CI

on:
  push:
    paths-ignore:
    - '**/*.md'
  pull_request:
    paths-ignore:
    - '**/*.md'

env:
  TERM: xterm

jobs:
  gcc:
    strategy:
      fail-fast: false
      matrix:
        arch: [x64, x86, ppc64le, armv7, aarch64]
        os: [ubuntu-18.04, ubuntu-latest]
    runs-on: ${{ matrix.os }}
    env:
      MATRIX_OS: ${{ matrix.os }}
      MATRIX_ARCH: ${{ matrix.arch }}
    steps:
    - uses: actions/checkout@v2
    - run: sh ./.github/scripts/all_tests.sh

  clang:
    strategy:
      fail-fast: false
      matrix:
        arch: [x64, x86]
        os: [ubuntu-18.04, ubuntu-latest]
    runs-on: ${{ matrix.os }}
    env:
      CC: clang
      MAXTRIX_OS: ${{ matrix.os }}
      MAXTRIX_ARCH: ${{ matrix.arch }}
    steps:
    - uses: actions/checkout@v2
    - run: sh ./.github/scripts/all_tests.sh


  macos:
    runs-on: macos-latest
    env:
      PKG_CONFIG_PATH: "/usr/local/opt/ncurses/lib/pkgconfig:$PKG_CONFIG_PATH"
    steps:
    - uses: actions/checkout@v2
    - run: |
        brew update
        brew install ncurses meson
    - run: |
        meson builddir
        ninja -v -C builddir
        ninja -C builddir dist
