name: Release
concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    tags:
      - v**

jobs:
  build:
    runs-on: ubuntu-20.04
    env:
      ARCH: x86_64
    steps:
    - uses: actions/checkout@v3
    - name: Prepare AppImage
      run: sh ./.github/scripts/all_tests.sh

    - name: Release AppImage
      uses: ncipollo/release-action@v1
      with:
        allowUpdates: True
        artifacts: "rmw*.AppImage*"
        token: ${{ secrets.GITHUB_TOKEN }}
        omitNameDuringUpdate: True
        omitBodyDuringUpdate: True
        replacesArtifacts: false
    - name: remove artifacts
      run: rm rmw*.AppImage*

