name: Release
concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    tags:
      - v**

jobs:
  build:
    runs-on: ubuntu-20.04
    env:
      ARCH: x86_64
    steps:
    - uses: actions/checkout@v3
    - name: Prepare AppImage
      run: sh ./.github/scripts/all_tests.sh
    - name: Release AppImage
      uses: ncipollo/release-action@v1
      with:
        allowUpdates: True
        artifacts: "rmw*.AppImage*"
        token: ${{ secrets.GITHUB_TOKEN }}
        omitNameDuringUpdate: True
        omitBodyDuringUpdate: True
        replacesArtifacts: false
    - name: remove artifacts
      run: rm rmw*.AppImage*

  build-deb:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
    - name: Copy debian directory
      run: cp -a packaging/debian .
    - uses: legoktm/gh-action-build-deb@debian-bullseye
      id: build-debian-bullseye
      with:
        args: --no-sign
        sources: deb http://deb.debian.org/debian bullseye-backports main
  #  - name: Create sha256sum
   #   run: sha256sum ${{ steps.build.outputs.filename }} > ${{ steps.build.outputs.filename }}.sha256sum
    - name: Release deb package
      uses: ncipollo/release-action@v1
      with:
        allowUpdates: True
        artifacts: "rmw*.deb*"
        token: ${{ secrets.GITHUB_TOKEN }}
        omitNameDuringUpdate: True
        omitBodyDuringUpdate: True
        replacesArtifacts: false
    #- name: remove artifacts
     # run: rm rmw*.AppImage*
